name: C++ CI

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies on ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        git clone https://github.com/microsoft/vcpkg build/vcpkg
        ./build/vcpkg/bootstrap-vcpkg.sh
        ./build/vcpkg/vcpkg install cpr nlohmann-json

    - name: Install dependencies on macos
      if: startsWith(matrix.os, 'macos')
      run: |
        git clone https://github.com/microsoft/vcpkg build/vcpkg
        ./build/vcpkg/bootstrap-vcpkg.sh
        ./build/vcpkg/vcpkg install cpr nlohmann-json

    - name: Install dependencies on windows
      if: startsWith(matrix.os, 'windows')
      run: |
        git clone https://github.com/microsoft/vcpkg build/vcpkg
        .\build\vcpkg\bootstrap-vcpkg.bat
        .\build\vcpkg\vcpkg install cpr nlohmann-json --triplet=x64-windows

    - name: Build
      shell: bash
      run: |
        cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=./build/vcpkg/scripts/buildsystems/vcpkg.cmake
        cmake --build build

    - name: Test
      run: cd build && ctest
